#!/usr/bin/env bash

trains_file="$1"  # A headerless CSV file containing tagbiljett arguments
prices_file="$2"  # a file to store the prices in (will be autogenerated)
email_address="$3"  # The email address to send the price changes to

old_prices=$(cat "${prices_file}")

> "${prices_file}"
while IFS=',' read -ra args; do
    echo "${args[@]}" >> "${prices_file}"
    tagbiljett "${args[@]}" >> "${prices_file}"
    echo "" >> "${prices_file}"
done < "${trains_file}"

prices_diff=$(diff <(echo "${old_prices}") <(cat "${prices_file}"))
if [ -n "${prices_diff}" ]; then
    echo "${prices_diff}" | mail -s "[tagbiljett] Ticket Price Change" "${email_address}"
fi
